docker image

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -85,20 +85,20 @@ jobs:
       # - name: Set up QEMU
       #   uses: docker/setup-qemu-action@v2
 
-      - name: Start database
-        run: |
-          docker compose up -d database
-
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
-        with:
-          driver-opts: |
-            network=container:database
-          buildkitd-flags: |
-            --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host
-      #           config-inline: |
-      #             [worker.oci]
-      #               max-parallelism = 1
+#      - name: Start database
+#        run: |
+#          docker compose up -d database
+#
+#      - name: Set up Docker Buildx
+#        uses: docker/setup-buildx-action@v3
+#        with:
+#          driver-opts: |
+#            network=container:database
+#          buildkitd-flags: |
+#            --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host
+#      #           config-inline: |
+#      #             [worker.oci]
+#      #               max-parallelism = 1
 
       - name: Build image
         id: docker_build
@@ -117,48 +117,48 @@ jobs:
             NEXT_PUBLIC_TELEMETRY_KEY=${{ env.NEXT_PUBLIC_TELEMETRY_KEY }}
             DATABASE_URL=postgresql://${{ env.POSTGRES_USER }}:${{ env.POSTGRES_PASSWORD }}@${{ env.DATABASE_HOST }}/${{ env.POSTGRES_DB }}
             DATABASE_DIRECT_URL=postgresql://${{ env.POSTGRES_USER }}:${{ env.POSTGRES_PASSWORD }}@${{ env.DATABASE_HOST }}/${{ env.POSTGRES_DB }}
-
-      - name: Test runtime
-        run: |
-          tags="${{ steps.meta.outputs.tags }}"
-          IFS=',' read -ra ADDR <<< "$tags"  # Convert string to array using ',' as delimiter
-          tag=${ADDR[0]}  # Get the first tag
-
-          docker run --rm --network stack \
-            -p 3000:3000 \
-            -e DATABASE_URL=postgresql://${{ env.POSTGRES_USER }}:${{ env.POSTGRES_PASSWORD }}@database/${{ env.POSTGRES_DB }} \
-            -e DATABASE_DIRECT_URL=postgresql://${{ env.POSTGRES_USER }}:${{ env.POSTGRES_PASSWORD }}@database/${{ env.POSTGRES_DB }} \
-            -e NEXTAUTH_SECRET=${{ env.NEXTAUTH_SECRET }} \
-            -e CALENDSO_ENCRYPTION_KEY=${{ env.CALENDSO_ENCRYPTION_KEY }} \
-            $tag &
-
-            server_pid=$!
-
-
-            echo "Waiting for the server to start..."
-            sleep 120
-
-            echo ${{ env.NEXT_PUBLIC_WEBAPP_URL }}/auth/login
-
-            for i in {1..60}; do
-              echo "Checking server health ($i/60)..."
-              response=$(curl -o /dev/null -s -w "%{http_code}" ${{ env.NEXT_PUBLIC_WEBAPP_URL }}/auth/login)
-              echo "HTTP Status Code: $response"
-              if [[ "$response" == "200" ]] || [[ "$response" == "307" ]]; then
-                echo "Server is healthy"
-                # Now, shutdown the server
-                kill $server_pid
-                exit 0
-              fi
-              sleep 1
-            done
-
-            echo "Server health check failed"
-            kill $server_pid
-            exit 1
-        env:
-          NEXTAUTH_SECRET: 'EI4qqDpcfdvf4A+0aQEEx8JjHxHSy4uWiZw/F32K+pA='
-          CALENDSO_ENCRYPTION_KEY: '0zfLtY99wjeLnsM7qsa8xsT+Q0oSgnOL'
+#
+#      - name: Test runtime
+#        run: |
+#          tags=solymamady/calcomImage
+#          IFS=',' read -ra ADDR <<< "$tags"  # Convert string to array using ',' as delimiter
+#          tag=${ADDR[0]}  # Get the first tag
+#
+#          docker run --rm --network stack \
+#            -p 3000:3000 \
+#            -e DATABASE_URL=postgresql://${{ env.POSTGRES_USER }}:${{ env.POSTGRES_PASSWORD }}@database/${{ env.POSTGRES_DB }} \
+#            -e DATABASE_DIRECT_URL=postgresql://${{ env.POSTGRES_USER }}:${{ env.POSTGRES_PASSWORD }}@database/${{ env.POSTGRES_DB }} \
+#            -e NEXTAUTH_SECRET=${{ env.NEXTAUTH_SECRET }} \
+#            -e CALENDSO_ENCRYPTION_KEY=${{ env.CALENDSO_ENCRYPTION_KEY }} \
+#            $tag &
+#
+#            server_pid=$!
+#
+#
+#            echo "Waiting for the server to start..."
+#            sleep 120
+#
+#            echo ${{ env.NEXT_PUBLIC_WEBAPP_URL }}/auth/login
+#
+#            for i in {1..60}; do
+#              echo "Checking server health ($i/60)..."
+#              response=$(curl -o /dev/null -s -w "%{http_code}" ${{ env.NEXT_PUBLIC_WEBAPP_URL }}/auth/login)
+#              echo "HTTP Status Code: $response"
+#              if [[ "$response" == "200" ]] || [[ "$response" == "307" ]]; then
+#                echo "Server is healthy"
+#                # Now, shutdown the server
+#                kill $server_pid
+#                exit 0
+#              fi
+#              sleep 1
+#            done
+#
+#            echo "Server health check failed"
+#            kill $server_pid
+#            exit 1
+#        env:
+#          NEXTAUTH_SECRET: 'EI4qqDpcfdvf4A+0aQEEx8JjHxHSy4uWiZw/F32K+pA='
+#          CALENDSO_ENCRYPTION_KEY: '0zfLtY99wjeLnsM7qsa8xsT+Q0oSgnOL'
 
       - name: Push image
         id: docker_push
@@ -168,8 +168,8 @@ jobs:
           file: ./Dockerfile
           push: true
           platforms: linux/amd64
-          tags: ${{ steps.meta.outputs.tags }}
-          labels: ${{ steps.meta.outputs.labels }}
+          tags: solymamady/calcomImage
+#          labels: ${{ steps.meta.outputs.labels }}
           build-args: |
             NEXT_PUBLIC_WEBAPP_URL=${{ env.NEXT_PUBLIC_WEBAPP_URL }}
             NEXT_PUBLIC_API_V2_URL=${{ env.NEXT_PUBLIC_API_V2_URL }}
@@ -181,7 +181,7 @@ jobs:
 
       - name: Image digest
         run: echo ${{ steps.docker_build.outputs.digest }}
-
-      - name: Cleanup
-        run: |
-          docker compose down
+#
+#      - name: Cleanup
+#        run: |
+#          docker compose down
